# Extract Data

In [ ]:
import pandas as pd

df = pd.read_csv(r'C:\Users\Sanket M\OneDrive\Documents\DATA_PIPELINE_DEVELOPMENT\data-pipeline.ipynb')
print(df)

# Data Preprocessing

In [ ]:
df.isnull().sum()

Disease          0
Symptom_1        0
Symptom_2        0
Symptom_3        0
Symptom_4      348
Symptom_5     1206
Symptom_6     1986
Symptom_7     2652
Symptom_8     2976
Symptom_9     3228
Symptom_10    3408
Symptom_11    3726
Symptom_12    4176
Symptom_13    4416
Symptom_14    4614
Symptom_15    4680
Symptom_16    4728
Symptom_17    4848
dtype: int64

In [ ]:
df.drop(columns=['Symptom_7','Symptom_8','Symptom_9','Symptom_10','Symptom_11','Symptom_12','Symptom_13','Symptom_14','Symptom_15','Symptom_16','Symptom_17'], inplace=True)
df.head(5)

,Disease,Symptom_1,Symptom_2,Symptom_3,Symptom_4,Symptom_5,Symptom_6
0,Fungal infection,itching,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN
1,Fungal infection,skin_rash,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN
2,Fungal infection,itching,nodal_skin_eruptions,dischromic _patches,NaN,NaN,NaN
3,Fungal infection,itching,skin_rash,dischromic _patches,NaN,NaN,NaN
4,Fungal infection,itching,skin_rash,nodal_skin_eruptions,NaN,NaN,NaN

In [ ]:
dict = {"Symptom_1":"s1", "Symptom_2":"s2", "Symptom_3":"s3", "Symptom_4":"s4","Symptom_5":"s5", "Symptom_6":"s6"}
df.rename(columns=dict, inplace= True)

In [ ]:
df.fillna('No Symptoms',inplace=True)

In [ ]:
df.isna().sum()

Disease    0
s1         0
s2         0
s3         0
s4         0
s5         0
s6         0
dtype: int64

# Transform Data

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df['Disease'] = le.fit_transform(df['Disease'])
df.tail(20)

,Disease,s1,s2,s3,s4,s5,s6
4900,20,fatigue,yellowish_skin,nausea,loss_of_appetite,yellowing_of_eyes,family_history
4901,21,joint_pain,vomiting,fatigue,yellowish_skin,dark_urine,nausea
4902,22,joint_pain,vomiting,fatigue,high_fever,yellowish_skin,dark_urine
4903,3,vomiting,yellowish_skin,abdominal_pain,swelling_of_stomach,distention_of_abdomen,history_of_alcohol_consumption
4904,36,chills,vomiting,fatigue,weight_loss,cough,high_fever
4905,10,continuous_sneezing,chills,fatigue,cough,high_fever,headache
4906,34,chills,fatigue,cough,high_fever,breathlessness,sweating
4907,13,constipation,pain_during_bowel_movements,pain_in_anal_region,bloody_stool,irritation_in_anus,No Symptoms
4908,18,vomiting,breathlessness,sweating,chest_pain,No Symptoms,No Symptoms
4909,39,fatigue,cramps,bruising,obesity,swollen_legs,swollen_blood_vessels
4910,26,fatigue,weight_gain,cold_hands_and_feets,mood_swings,lethargy,dizziness
4911,24,fatigue,mood_swings,weight_loss,restlessness,sweating,diarrhoea
4912,25,vomiting,fatigue,anxiety,sweating,headache,nausea
4913,31,joint_pain,neck_pain,knee_pain,hip_joint_pain,swelling_joints,painful_walking
4914,5,muscle_weakness,stiff_neck,swelling_joints,movement_stiffness,painful_walking,No Symptoms
4915,0,vomiting,headache,nausea,spinning_movements,loss_of_balance,unsteadiness
4916,2,skin_rash,pus_filled_pimples,blackheads,scurring,No Symptoms,No Symptoms
4917,38,burning_micturition,bladder_discomfort,foul_smell_of urine,continuous_feel_of_urine,No Symptoms,No Symptoms
4918,35,skin_rash,joint_pain,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails
4919,27,skin_rash,high_fever,blister,red_sore_around_nose,yellow_crust_ooze,No Symptoms

In [ ]:
df['s1'] = le.fit_transform(df['s1'])
df['s2'] = le.fit_transform(df['s2'])
df['s3'] = le.fit_transform(df['s3'])
df['s4'] = le.fit_transform(df['s4'])
df['s5'] = le.fit_transform(df['s5'])
df['s6'] = le.fit_transform(df['s6'])
df.head(20)

    Disease  s1  s2  s3  s4  s5  s6
0        15  33  35  35  11  38  32
1        15  24  27  18  50  38  32
2        15  33  27  18  50  38  32
3        15  33  35  18  50  38  32
4        15  33  35  35  50  38  32
5        15  24  27  18  50  38  32
6        15  33  27  18  50  38  32
7        15  33  35  18  50  38  32
8        15  33  35  35  50  38  32
9        15  33  35  35  11  38  32
10        4   8  33  11  45  38  32
11        4  23   9  50  50  38  32
12        4   8   9  50  50  38  32
13        4   8  33  50  50  38  32
14        4   8  33  11  50  38  32
15        4  23   9  50  50  38  32
16        4   8   9  50  50  38  32
17        4   8  33  50  50  38  32
18        4   8  33  11  50  38  32
19        4   8  33  11  45  38  32

# Load Data

In [ ]:
df.to_csv("processed_data.csv", index=False)